project: 
  type: website
  
website:
  title: 'GEPD \n Implementation Package'
  back-to-top-navigation: true
  page-navigation: true
  page-footer: 'Copyright 2023, Global Education Policy Dashboard'
  sidebar: 
    background: info
    type: 'dark'
    search: true
    style: 'docked'
    contents:
      - section: 'Introduction'
        contents: 
          - index.qmd
          - package.qmd
      - section: 'Implementation Package'
        contents:
          - s1_confirm-country.qmd
          - s2_select-sample.qmd
          - s3_approvals.qmd
          - s4_survey-firm.qmd
          - s5_field-work.qmd
          - s6_enumerators.qmd
          - s7_data-collection.qmd
          - s8_computing.qmd
          - s9_validation.qmd
          - s10_publishing.qmd
      