---
title: "2. Selecting Sample"
format: 
  html:
    shiny: true
---

<div style="margin-top: 30px;"></div>

The Global Education Policy Dashboard (GEPD) uses a two-stage random sampling method for collecting representative and quality data. Initially, schools are selected through a stratified sampling based on urban/rural classification and, if needed, geographical regions. This step guarantees a diverse and accurate representation of the nation's schools. The second stage involves randomly selecting teachers and students from these schools for interviews and assessments.

::: panel-tabset
### School Sampling

#### **Request & Receive the Country's List of Schools**

The Sampling Tool can only be used when the Country share the **Country's List of Schools** file, that can also be downloaded here [School List](https://github.com/ArthurCheib/gepd-implementation-pck/raw/main/websites-materials/step-1/SB4_School_Information.xlsx){.btn .btn-primary} - this is the same list previously discussed with country at the [substep 1.4 of Confirming Country's Participation](https://arthurcheib.github.io/gepd-implementation-pck/s1_confirm-country.html#next-steps-email-following-up-after-initial-meeting). Such list contains the following columns, to be populated:

-   **Name of School:** Official name of the educational institution.

-   **Region:** Geographical region where the school is located.

-   **District:** Administrative district of the school's location.

-   **City:** City or town where the school is situated.

-   **Geographic Location:** School's specific geographical coordinates.

-   **Urban or Rural Indicator:** Classification as urban or rural.

-   **Type of School:** Category or kind of school (e.g., primary).

-   **Type of Property:** Ownership status of the school building.

-   **Does the school have a second shift? Yes/No:** Indicator of dual-shift system.

-   **1st Grade Total Number of Students:** Total students in 1st grade.

-   **2nd Grade Total Number of Students:** Total students in 2nd grade.

-   **3rd Grade Total Number of Teachers:** Total teachers for 3rd grade.

-   **th Grade Total Number of Teachers:** Total teachers for 4th grade.

-   **5th Grade Total Number of Students:** Total students in 5th grade.

-   **6th Grade Total Number of Students:** Total students in 6th grade.

-   **1st Grade Total Number of Teachers:** Total teachers for 1st grade.

-   **2nd Grade Total Number of Teachers:** Total teachers for 2nd grade.

-   **3rd Grade Total Number of Teachers:** Total teachers for 3rd grade.

-   **4th Grade Total Number of Teachers:** Total teachers for 4th grade.

-   **5th Grade Total Number of Teachers:** Total teachers for 5th grade.

-   **6th Grade Total Number of Teachers:** Total teachers for 6th grade.

#### **Sampling Rules:**

The rules for running the random stratification when sampling are:

- **Sample size:** GEPD common sample size is of 200 to 300 schools;
- **Stratification:** GEPD uses the rural/urban classification as a Strata when sampling. The region column is optional, but including it can influence the overall sample size
- **Minimum of students:** to qualify as a valid sample school, each school must have a minimum of three (3) students in both 1st and 4th grades.

#### **Steps for Using the Sampling Tool:**

-   Upload your excel or csv file containing the list of schools
-   Choose the sample size of schools (from 200 to 300 sample size)
-   Choose one or two columns that you want to use for stratification
-   Run the sampling!
-   Visualize the schools selected
-   Download your file containing the schools sampled
-   Document the steps of your sampling process
-   Reach out to the Central Team as needed

<iframe src="https://arthurcheib.shinyapps.io/gepd-sampling/" style="border: none; width: 100%; height: 800px;">

</iframe>

This Sampling Tool was created to assist you during the Sampling Process of GEPD's Implementation. You can also access the source code used to generate the stratified sample by downloading it: [Download Sampling R Code](https://github.com/ArthurCheib/gepd-implementation-pck/raw/main/websites-materials/step-2/gepd-sampling.R.zip){.btn .btn-primary target="_blank"}

### Public Officials Sampling

In the GEPD implementation, the sampling of public officials involves selecting 200 public education officials, focusing on personnel from both central and regional/district offices of the Ministry of Education. The sampling utilizes a cluster strategy. However, most commonly, instead of receiving a direct list of public officials, GEPD is typically provided with a list of regional and district public office locations.

Based on this, 10 regional offices are randomly selected from the regions corresponding to the school survey. In each region, one district office is chosen. Within these offices, the sampling includes 7 officials: the head of the office, the HR director, and five randomly chosen officials from finance and planning.

The federal level sampling is conducted in collaboration with the Ministry of Education, focusing on key offices, where the director and a random selection of officials are interviewed. This stratified approach ensures comprehensive coverage from school to district, regional, and central offices.

#### **Step-by-step**

1.  Receive Office Locations List
2.  Select Regional Offices: randomly choose 10 regional offices from the provided list, ensuring they align with the regions where schools were surveyed.
3.  Choose District Offices: In each selected region, randomly pick one district office
4.  Sample Officials in Offices:
    -   In each regional/district office, randomly select 7 officials, including the office head, HR director, and five officials from finance and planning.
    -   At the federal level, work with the Ministry of Education to identify relevant offices. Interview the office director and a random number of staff members.
5.  Document the sampling process
:::
