---
title: "3. Obtaining Approvals"
format: html
editor: visual
---

## Approvals Process

Obtaining necessary approvals is essential for beginning the data collection process. Since approval requirements vary by country, this step provides a list of common approvals. The examples provided are from previous implementations, but GEPD's implementation team should always meet country-specific regulatory needs.

Certain approvals are necessary to ensure ethical standards are met, particularly when the data collection involves sensitive activities such as interviewing and assessing children, as well as conducting classroom observations. These approvals safeguard the rights and well-being of participants, especially minors.

Sample of Types of Approvals that might be needed:

1.  Ethical Approval - (if applicable).
2.  Approvals requested from the National Statistics Agency - (if applicable).

The Approvals topic can be approached during the [Initial Meeting](https://arthurcheib.github.io/gepd-implementation-pck/s1_confirm-country.html#conducting-the-meeting), where the specific approvals required in the country through for the data collection can be clarified in the discussions with government officials.

To comprehensively address these requirements, the local team must collaborate closely with the Survey Firm. In most implementations, it is the Survey Firm that bears the primary responsibility for securing all necessary approvals, ensuring that the data collection process adheres to both local and international ethical guidelines.
