---
title: "5. Preparing Field Work"
format: html
editor: source
---

<div style="margin-top: 30px;"></div>

Step 5 focuses on preparing the field work. This step begins with a detailed onboarding email for the selected survey firm, ensuring they are well-informed and equipped with all necessary resources. The email should also contain an invitation for a kick-off meeting to align everyone's understanding of the project scope, timeline, and specific roles.

This step ensures that both the Task Team Leader (TTL) and the survey firm are fully prepared to execute the field work efficiently, addressing any potential questions and closely supervising the firm's preparations to ensure adherence to the GEPD's project standards.

<div style="margin-top: 50px;"></div>

## Step-by-step Guide

#### **1. Email for Onboarding the Survey Firm:**

The onboarding email to the survey firm marks the beginning of Step 5. It formally welcomes the firm and provides essential information and resources for the project. The email - a sample of it can be downloaded below too - should include attached the following documents:

**1.2 - RESOURCES AVAILABLE:**

- **School Survey Instrument:** [English](https://github.com/ArthurCheib/gepd-implementation-pck/raw/main/websites-materials/step-1/SB2_GEPD%20Implementation%20Brief/SB2_GEPD%20Implementation%20Brief.pdf)
|
[French](https://github.com/ArthurCheib/gepd-implementation-pck/raw/main/websites-materials/step-1/SB2_GEPD%20Implementation%20Brief/SB2_GEPD-IMPLEMENT-Brief-French.pdf)
|
[Spanish]()
|
[Arabic]()
|
[Portuguese]()

- **Manual of the School Survey:**
[English](https://github.com/ArthurCheib/gepd-implementation-pck/raw/main/websites-materials/step-1/SB2_GEPD%20Implementation%20Brief/SB2_GEPD%20Implementation%20Brief.pdf)
|
[French](https://github.com/ArthurCheib/gepd-implementation-pck/raw/main/websites-materials/step-1/SB2_GEPD%20Implementation%20Brief/SB2_GEPD-IMPLEMENT-Brief-French.pdf)
|
[Spanish]()
|
[Arabic]()
|
[Portuguese]()

- **Step-by-step Guide for the School Survey:**
[English](https://github.com/ArthurCheib/gepd-implementation-pck/raw/main/websites-materials/step-1/SB2_GEPD%20Implementation%20Brief/SB2_GEPD%20Implementation%20Brief.pdf)
|
[French](https://github.com/ArthurCheib/gepd-implementation-pck/raw/main/websites-materials/step-1/SB2_GEPD%20Implementation%20Brief/SB2_GEPD-IMPLEMENT-Brief-French.pdf)
|
[Spanish]()
|
[Arabic]()
|
[Portuguese]()

- **Survey of Public Officials Instrument:**
[English](https://github.com/ArthurCheib/gepd-implementation-pck/raw/main/websites-materials/step-1/SB2_GEPD%20Implementation%20Brief/SB2_GEPD%20Implementation%20Brief.pdf)
|
[French](https://github.com/ArthurCheib/gepd-implementation-pck/raw/main/websites-materials/step-1/SB2_GEPD%20Implementation%20Brief/SB2_GEPD-IMPLEMENT-Brief-French.pdf)
|
[Spanish]()
|
[Arabic]()
|
[Portuguese]()

- **Manual of the Survey of Public Officials:**
[English](https://github.com/ArthurCheib/gepd-implementation-pck/raw/main/websites-materials/step-1/SB2_GEPD%20Implementation%20Brief/SB2_GEPD%20Implementation%20Brief.pdf)
|
[French](https://github.com/ArthurCheib/gepd-implementation-pck/raw/main/websites-materials/step-1/SB2_GEPD%20Implementation%20Brief/SB2_GEPD-IMPLEMENT-Brief-French.pdf)
|
[Spanish]()
|
[Arabic]()
|
[Portuguese]()

- **Step-by-step Guide for the Survey of Public Officials:**
[English](https://github.com/ArthurCheib/gepd-implementation-pck/raw/main/websites-materials/step-1/SB2_GEPD%20Implementation%20Brief/SB2_GEPD%20Implementation%20Brief.pdf)
|
[French](https://github.com/ArthurCheib/gepd-implementation-pck/raw/main/websites-materials/step-1/SB2_GEPD%20Implementation%20Brief/SB2_GEPD-IMPLEMENT-Brief-French.pdf)
|
[Spanish]()
|
[Arabic]()
|
[Portuguese]()

- **Recordings of Previous Survey Firm's Training:**
[English](https://github.com/ArthurCheib/gepd-implementation-pck/raw/main/websites-materials/step-1/SB2_GEPD%20Implementation%20Brief/SB2_GEPD%20Implementation%20Brief.pdf)
|
[French](https://github.com/ArthurCheib/gepd-implementation-pck/raw/main/websites-materials/step-1/SB2_GEPD%20Implementation%20Brief/SB2_GEPD-IMPLEMENT-Brief-French.pdf)
|
[Spanish]()
|
[Arabic]()
|
[Portuguese]()

In addition, the email outlines the immediate steps for the firm, which include:
-   Adapting instruments to the Country of implementation's reality
-   Planning on translations of the Instruments - if applicable
-   Inviting the Firm to a kick-off meeting.

<div style="margin-top: 50px;"></div>

#### **2. Kick-off Meeting with the Firm**

The kick-off meeting, is the space for the TTL to ensure that the project's scope, timeline, and roles are all clear for the survey firm. It's the moment to go through the contract details, including deliverables and quality standards, so addressing initial questions and setting clear expectations are key. The TTL should highlight critical milestones and discuss immediate preparatory steps.

As a resource, this **Meeting's FAQ** might prove useful: 
[English](https://github.com/ArthurCheib/gepd-implementation-pck/raw/main/websites-materials/step-1/SB2_GEPD%20Implementation%20Brief/SB2_GEPD%20Implementation%20Brief.pdf)
|
[French](https://github.com/ArthurCheib/gepd-implementation-pck/raw/main/websites-materials/step-1/SB2_GEPD%20Implementation%20Brief/SB2_GEPD-IMPLEMENT-Brief-French.pdf)
|
[Spanish]()
|
[Arabic]()
|
[Portuguese]()

<div style="margin-top: 50px;"></div>

#### **3. Supervising the Preparations of the Firm**

The final step of Preparing the Field Work concerns the TTL responsibility of supervising the survey firm’s preparations, ensuring they meet GEPD standards and adhere to project timelines. This role might involve:

-   Ensuring the Survey Firm have access to all necessary materials
-   Overseeing the Survey Firm’s training process and pre-tests of the tools
-   Overseeing the instrument adaptation, translations and elaboration of the field protocols
-   Addressing the Survey Firm questions about the survey methodologies

The TTL must also confirm that logistical plans for field work are finalized. Regular check-ins are key for assessing the firm’s progress and addressing potential issues promptly.
